
## NumPy
- numPy is a powerful library in python for numerical computations, handling multi-dimensional arrays and matrices with efficiency.

### core functionalities:
- Array
- Vectorization
- Broadcasting
- Universal Functions (ufuncs)
- Indexing and Slicing
- Reshaping
- Aggregation Functions
- Linear Algebra Operations

### Array
#### definition 
concise:
- a homogeneous, fixed-size container for elements (usually numbers)
- enables contiguous memory layout and high-performance computation

elaborate:
- A NumPy array is a grid of values, all of the same type, indexed by a tuple of non-negative integers.
- The number of dimensions is the rank of the array, and the shape of an array is a tuple of integers giving the size of the array along each dimension.

#### explanation

- NumPy arrays are the core data structure of the NumPy library.
- Unlike Python lists, NumPy arrays are homogeneous (all elements must be of the same type) and provide memory-efficient storage and faster operations.
- They enable vectorized operations, eliminating the need for explicit loops, which makes code more concise and typically runs much faster.

#### examples:

##### 1. The Core: NumPy Arrays (ndarray)

1.1 Importing

1.2 Creating Arrays

- 1.2.1 From a Python list
   - simple
   - list of lists
- 1.2.2 Using built-in functions
   - array of zeros
   - array of ones
   - np.arrange (like py range)
   - np.linspace

In [5]:
# 1.1 Importing

import numpy as np

In [6]:
# 1.2 Creating Arrays

In [ ]:
#  1.2.1 From a Python list
#   - simple
#   - list of lists

In [7]:
# 1) From a Python list
list_a = [1, 2, 3, 4, 5] # simple python list
np_array_a = np.array(list_a)
print(f"Array A: {np_array_a}")
print(f"Type of np_array_a: {type(np_array_a)}") # <class 'numpy.ndarray'>
print(f"Data type of elements: {np_array_a.dtype}") # e.g., int64 or int32

list_b = [[1, 2], [3, 4], [5, 6]] # List of lists
np_array_b = np.array(list_b)
print(f"Array B (2D):\n{np_array_b}")
print(f"Shape of Array B: {np_array_b.shape}") # (3, 2) -> 3 rows, 2 columns

Array A: [1 2 3 4 5]
Type of np_array_a: <class 'numpy.ndarray'>
Data type of elements: int64
Array B (2D):
[[1 2]
 [3 4]
 [5 6]]
Shape of Array B: (3, 2)


In [ ]:
#  1.2.2 Using built-in functions
#   - array of zeros
#   - array of ones
#   - np.arrange (like py range)
#   - np.linspace

In [8]:
# 2) Using built-in functions
zeros_array = np.zeros((2, 4)) # 2x4 array of zeros
print(f"Zeros array:\n{zeros_array}")

ones_array = np.ones((3, 3)) # 3x3 array of ones
print(f"Ones array:\n{ones_array}")

range_array = np.arange(0, 10, 2) # Like Python's range, but creates an array [0 2 4 6 8]
print(f"Range array: {range_array}")

linspace_array = np.linspace(0, 1, 5) # 5 evenly spaced numbers between 0 and 1 (inclusive)
print(f"Linspace array: {linspace_array}")

Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


##### 2. Vectorization & Basic Operations
